### ISSUE TITLE
Flutter v1.22.1 - Compatibility error

### ISSUE THREAD

**Issue by Naveenkumar3506** [macif-dev/ssl_pinning_plugin#13]
Hi, I am getting below error. can you please assist quickly on this. Thanks in advance.

Invalid plugin specification ssl_pinning_plugin.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by dokinkon** [comment]
Same issue

**Comment by dokinkon** [comment]
> Hi, I am getting below error. can you please assist quickly on this. Thanks in advance.
> 
> Invalid plugin specification ssl_pinning_plugin.
> Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

@Naveenkumar3506 You can use following repository to resolve this issue temporally.
```
ssl_pinning_plugin:
    git:
      url: git@github.com:adsellor/ssl_pinning_plugin.git
```

@us3soap Please approve the pull request about this issue, thanks.

**Comment by us3soap** [comment]
Thx for the PR.

I publish the package today

**Comment by Naveenkumar3506** [comment]
> Hi, I am getting below error. can you please assist quickly on this. Thanks in advance.
> 
> Invalid plugin specification ssl_pinning_plugin.
> Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

Still the above issue exist


> I publish the package today

Hi did you publish already?.

**Comment by us3soap** [comment]
I just uploaded now. 

Sorry for the delay
