### ISSUE TITLE
error: compiling for iOS 8.0, but module 'CryptoSwift' has a minimum deployment target of iOS 9.0

### ISSUE THREAD

**Issue by dokinkon** [macif-dev/ssl_pinning_plugin#8]
Here is the latest version of  ssl_pining_plugin.pubspec
```
Pod::Spec.new do |s|
  s.name             = 'ssl_pinning_plugin'
  s.dependency 'CryptoSwift'
  s.ios.deployment_target = '8.0'
end
```

And according the CHANGELOG of **CryptoSwift**, the minimum deployment target is **iOS9.0**.

Therefore I can't build app successfully.

Could you please bump `s.ios.deployment.target` to '9.0' or specify version constraint of **CryptoSwift**?

Thanks.

**Comment by us3soap** [comment]
Thanks for your PR.

`s.ios.deployment.target` is '9.0' now
